# Generated by Django 4.1.4 on 2023-01-14 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegclassic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classicinfomodel',
            name='prize',
        ),
        migrations.AddField(
            model_name='classicinfomodel',
            name='Large',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='classicinfomodel',
            name='Medium',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='classicinfomodel',
            name='Small',
            field=models.IntegerField(null=True),
        ),
    ]
