# Generated by Django 4.1.4 on 2023-01-14 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NonVegClassicModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pizza', models.CharField(max_length=35)),
                ('Small', models.IntegerField()),
                ('Medium', models.IntegerField()),
                ('Large', models.IntegerField()),
            ],
        ),
    ]
