# Generated by Django 4.1.4 on 2023-01-09 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BookTableModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bname", models.CharField(max_length=25)),
                ("badd", models.CharField(max_length=50)),
                ("btotalPerson", models.IntegerField()),
            ],
        ),
    ]
