# Generated by Django 4.1.4 on 2023-01-09 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booktable", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="booktablemodel", old_name="badd", new_name="Add",
        ),
        migrations.RenameField(
            model_name="booktablemodel", old_name="bname", new_name="Name",
        ),
        migrations.RenameField(
            model_name="booktablemodel", old_name="btotalPerson", new_name="Person",
        ),
    ]
