# Generated by Django 4.1.4 on 2023-01-13 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Burger', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BurgerInfoModel',
        ),
    ]
